### ISSUE TITLE
opencc组件失效

### ISSUE THREAD

**Issue by yanhuacuo** [hchunhui/ibus-rime.AppImage#1]
opencc组件不工作，「繁简转换」

以前二进制模式从仓库里装ibus-rime时，schema 文件下，调用opencc组件实现繁简转换一直是正常的。

```
switches:
  - name: zh_trad
    reset: 0
    states: [ 简,繁 ]



engine:
  filters:
    - charset_filter@gb2312  
    - simplifier



simplifier:
  opencc_config: s2t.json
  option_name: zh_trad


key_binder:
  bindings: 
    - {accept: "Control+Shift+F", toggle: zh_trad, when: always}
```

现在这份无依赖包，繁简转换失效了。

请求查验
